os: osx
language: objective-c
osx_image: xcode8

script: 
  - set -o pipefail
  - xcodebuild build-for-testing test-without-building -project RxStarscream.xcodeproj -scheme RxStarscream -sdk iphonesimulator -destination "name=iPhone SE" | xcpretty -c